### ISSUE TITLE
Saving a file from a menu does not work in LInux

### ISSUE THREAD

**Issue by zag** [zag/podlite-desktop#22]
![image](https://user-images.githubusercontent.com/31441/147958869-e86f8e87-820c-4955-86d9-87b924141e04.png)

**Comment by finanalyst** [comment]
Ctrl-S works, but the menu item did not.
The menu item for Open works, and is the same as Ctrl-O

**Comment by zag** [comment]
fixed!
will be  available in coming v0.2.1 release
thank you!
