### ISSUE TITLE
More menu items

### ISSUE THREAD

**Issue by finanalyst** [zag/podlite-desktop#23]
I find  
New - create a new document with blank, and   
Save-As - save the current contents with a new file name  
to be useful.

I could not find a way to start a new file.
I finished working on one document. So I wanted to start a new document. 

I have to go in and out of Podlite to do this.

**Comment by zag** [comment]
@finanalyst, implemented. 
Will avalable in coming v0.2.1 release. 
thank you for feedback!
<img src="https://user-images.githubusercontent.com/31441/148654655-7ccb4bb7-5ff6-42f4-b7a2-40228a5d6ef9.png" width="400"  />
