### ISSUE TITLE
Should it ignore Raku code?

### ISSUE THREAD

**Issue by FCO** [zag/podlite-desktop#3]
Should it ignore Raku code? When I open my module's code on it, it shows its code as a not well-indented code on preview panel. Could it ignore Raku code?

![image](https://user-images.githubusercontent.com/99834/88207568-e54d1580-cc47-11ea-9e6e-a069f67c6462.png)

**Comment by zag** [comment]
Hello Fernando,
Yes it's ok.
At this moment Podlite,  doesn't detect code blocks.  And stay it pod mode
by default.
With best,
Alex

ср, 22 июл. 2020 г., 20:20 Fernando Correa de Oliveira <
notifications@github.com>:

**Comment by zag** [comment]
Check release v0.0.2.
thank you!
